### PR TITLE
Binarywritter modifications

### PR DESCRIPTION
**Pull request by 2gud4u**
Modified App.js to "work" with weather widget, added Utilsweather.js , dateformat.css also, and several methods. The app needs yarn add whatwg-fetch to be able to run.

### CODE REVIEW

**Comment by Apollon77** [comment]
What is yarn needed for?

@bluefox: I have no idea about the license stuff with the two new introduced files ... and PR vs license at all ....

**Comment by 2gud4u** [comment]
> What is yarn needed for?
> 
> @bluefox: I have no idea about the license stuff with the two new introduced files ... and PR vs license at all ....

@Apollon77 yarn its like npm but faster i think whatwg-fetch "package" needs to be added in order to modifications to work

**Comment by Apollon77** [comment]
I know what yarn is, but we decided to rely on npm and will not change to yarn.

Is this maybe also the reson for the failing tests for your PR: https://travis-ci.org/ioBroker/ioBroker.material/builds/428469850

**Comment by GermanBluefox** [comment]
Cannot compile the code.

**Pull request closed without merging**
